server:
  port: 8081
  servlet:
    context-path: /posts

spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
  application:
    name: posts
